### ISSUE TITLE
Make anything using flutter widget.

### ISSUE THREAD

**Issue by hiashutoshsingh** [hiashutoshsingh/FlutterLearning#1]

**Comment by namita2310** [comment]
I would like to do it.

**Comment by namita2310** [comment]
@hiashutoshsingh Could you also add hacktoberfest,hacktoberfest-accepted label. lt would be a great hep to me

**Comment by hiashutoshsingh** [comment]
> I would like to do it.

sure go ahead.

**Comment by namita2310** [comment]
@hiashutoshsingh could you please review my PR

**Comment by rahul975337** [comment]
can i do it?
Also can you please add the hacktoberfest, hacktoberfest-accepted label , it would help me

**Comment by hiashutoshsingh** [comment]
> can i do it?
> Also can you please add the hacktoberfest, hacktoberfest-accepted label , it would help me

sure go ahead and raise PR it has all the lables in it.

**Comment by Sutiksh** [comment]
Can I add any app?
